export interface Topic {
  title: string
  content: string
  code?: string
}

export interface Chapter {
  id: string
  number: number
  title: string
  subtitle: string
  icon: string
  color: string
  topics: Topic[]
}

export const chapters: Chapter[] = [
  {
    id: 'ch1',
    number: 1,
    title: 'Exception Handling',
    subtitle: 'Run-time error management in Java',
    icon: 'ShieldAlert',
    color: 'neon-text-blue',
    topics: [
      {
        title: 'What is an Exception?',
        content: `An exception is an event that occurs during the execution of a program that disrupts the normal flow of instructions. Exceptions can be generated by the JVM or manually by your code using a throw statement.

The three main causes of exceptions:
(a) An abnormal execution condition detected by the JVM — e.g., integer divided by zero, linking failure, resource exhaustion
(b) A throw statement executed in Java code
(c) An asynchronous exception — e.g., Thread.stop() or internal JVM error

Java exception handling is managed via five keywords: try, catch, throw, throws, and finally.`,
        code: `// Basic exception structure
try {
    int d = 0;
    int a = 42 / d; // throws ArithmeticException
} catch (ArithmeticException e) {
    System.out.println("Division by zero: " + e);
} finally {
    System.out.println("Always executes");
}`
      },
      {
        title: 'Throwable Class Hierarchy',
        content: `A Java exception is an instance of the Throwable class or one of its extensions.

Throwable
├── Error (unchecked — JVM-level problems, usually unrecoverable)
│   └── OutOfMemoryError, StackOverflowError...
└── Exception
    ├── RuntimeException (unchecked)
    │   ├── ArithmeticException
    │   ├── NullPointerException
    │   ├── ArrayIndexOutOfBoundsException
    │   ├── ClassCastException
    │   └── NumberFormatException
    └── Checked Exceptions
        ├── IOException → FileNotFoundException, EOFException
        └── ClassNotFoundException`
      },
      {
        title: 'Checked vs Unchecked Exceptions',
        content: `Unchecked exceptions: instances of Error, RuntimeException, and their subclasses. Not required to be declared or caught. You are usually at fault (e.g., NullPointerException — you should test for null).

Checked exceptions: all other subclasses of Exception. The compiler checks that they are either caught in a try-catch or declared with throws. Caused by external circumstances (disk errors, network failures).

Rule: All exceptions that belong to subclasses of RuntimeException are unchecked; all other subclasses of Exception are checked.`,
        code: `// Checked exception — must handle or declare
public void readFile(String name) throws IOException {
    FileReader fr = new FileReader(name); // FileNotFoundException (checked)
}

// Unchecked — compiler won't force you to handle
int[] arr = new int[5];
arr[10] = 1; // ArrayIndexOutOfBoundsException`
      },
      {
        title: 'Multiple Catch & Clause Order',
        content: `When using multiple catch statements, subclasses MUST come before superclasses. A catch using a superclass will catch exceptions of that type PLUS any of its subclasses — a subclass after its superclass is unreachable code (compile-time error in Java).

The finally clause: executes whether or not an exception was thrown. Use it for cleanup (closing files, connections). Guaranteed to run when the try block is exited in any of three ways:
1. After completing the last statement in the try block
2. After completing the last statement of a catch clause
3. When an exception was thrown in the try block and not caught`,
        code: `class MultiCatch {
    public static void main(String[] args) {
        try {
            int a = args.length;
            int b = 42 / a;           // ArithmeticException if a==0
            int[] c = {1};
            c[42] = 99;               // ArrayIndexOutOfBoundsException
        } catch (ArithmeticException e) {
            System.out.println("Divide by 0: " + e);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Array index oob: " + e);
        } finally {
            System.out.println("Always runs");
        }
    }
}`
      },
      {
        title: 'throw and throws Keywords',
        content: `throws: Used in a method signature to declare that the method can throw a checked exception. The calling method must then handle or re-declare it.

throw: Used to explicitly throw an exception from a method body. Execution stops immediately after throw; subsequent statements are skipped.

Syntax for throw: throw new ExceptionType("message");
You can throw a new instance inline without storing in a variable.`,
        code: `// throws — declares the exception
private int quotient(int num, int den) throws ArithmeticException {
    return num / den;
}

// throw — explicitly raises exception
public void withdraw(double amount) {
    if (amount > balance) {
        throw new IllegalArgumentException("Amount exceeds balance");
    }
    balance -= amount;
}

// Multiple throws declarations
public void read(String filename) throws IOException, ClassNotFoundException {
    // ...
}`
      },
      {
        title: 'User-Defined Exceptions',
        content: `A custom exception class must extend an existing exception class (directly or indirectly extending Throwable). It inherits methods from Throwable. Design your own when none of the standard exception types describe your particular error condition.`,
        code: `// Custom exception class
public class UserDefinedException extends Exception {
    public UserDefinedException() {
        System.out.println("Wrong data has been entered");
    }
    public UserDefinedException(String msg) {
        super(msg);
    }
}

// Using the custom exception
public class UserTrial {
    private int num1, num2;
    public UserTrial(int a, int b) { num1 = a; num2 = b; }

    public void show() throws UserDefinedException {
        if (num1 < 0 || num2 > 0)
            throw new UserDefinedException("Wrong data entered");
        else
            System.out.println("Values: " + num1 + " and " + num2);
    }

    public static void main(String[] args) {
        UserTrial t = new UserTrial(-1, 1);
        try {
            t.show();
        } catch (UserDefinedException e) {
            System.err.println("Illegal values entered");
        }
    }
}`
      }
    ]
  },
  {
    id: 'ch2',
    number: 2,
    title: 'Input-Output Streams',
    subtitle: 'The java.io package — Byte & Character streams',
    icon: 'ArrowLeftRight',
    color: 'neon-text-cyan',
    topics: [
      {
        title: 'Stream Fundamentals',
        content: `In Java, I/O is abstracted as a flow of data called a stream. A stream is a sequence of bytes (or characters) that flows from a source to a destination.

The java.io package splits into two hierarchies:
• Byte Stream Classes — handle raw binary data (8-bit bytes)
  - InputStream (abstract base for reading bytes)
  - OutputStream (abstract base for writing bytes)
• Character Stream Classes — handle Unicode text (16-bit chars)
  - Reader (abstract base for reading characters)
  - Writer (abstract base for writing characters)

All streams ultimately connect to one of three destinations: Memory, File, or Pipe.`
      },
      {
        title: 'Byte Stream Classes',
        content: `InputStream key methods:
• int read() — reads one byte, returns -1 at end-of-stream
• int read(byte[] b) — reads into array, returns count or -1
• int available() — returns estimated bytes available
• long skip(long n) — skips n bytes
• void close() — closes the stream

OutputStream key methods:
• void write(int b) — writes one byte
• void write(byte[] b) — writes byte array
• void flush() — flushes buffered output
• void close() — closes the stream`,
        code: `// Reading a file byte-by-byte
FileInputStream fis = new FileInputStream("data.bin");
int byteData;
while ((byteData = fis.read()) != -1) {
    System.out.print(byteData + " ");
}
fis.close();`
      },
      {
        title: 'Character Stream Classes',
        content: `Reader key methods:
• int read() — reads one char, returns -1 at end
• int read(char[] cbuf) — reads into char array
• void close()

Writer key methods:
• void write(int c) — writes one char
• void write(String s) — writes a string
• void flush()
• void close()

Use character streams for text files. Use byte streams for binary files (images, audio, etc.).`,
        code: `// Character stream example
FileReader fr = new FileReader("text.txt");
int ch;
while ((ch = fr.read()) != -1) {
    System.out.print((char) ch);
}
fr.close();

// Writer example
FileWriter fw = new FileWriter("output.txt");
fw.write("Hello, Java Streams!");
fw.close();`
      }
    ]
  },
  {
    id: 'ch3',
    number: 3,
    title: 'Specialized Stream Implementations',
    subtitle: 'File, Data, Buffered & Sequence streams',
    icon: 'Database',
    color: 'neon-text-violet',
    topics: [
      {
        title: 'File Streams',
        content: `FileInputStream / FileOutputStream — concrete byte-stream classes for reading/writing raw file bytes.
FileReader / FileWriter — concrete character-stream classes for reading/writing text files.

FileWriter append mode: pass true as second argument to append to existing file rather than overwrite.`,
        code: `// FileInputStream — read file bytes
FileInputStream fis = new FileInputStream("image.png");
byte[] buffer = new byte[1024];
int bytesRead;
while ((bytesRead = fis.read(buffer)) != -1) {
    // process buffer[0..bytesRead-1]
}
fis.close();

// FileWriter — write text
FileWriter fw = new FileWriter("log.txt", true); // append mode
fw.write("New log entry\n");
fw.close();`
      },
      {
        title: 'DataInputStream / DataOutputStream',
        content: `These are filter streams that wrap another stream and allow reading/writing of Java primitive data types in a machine-independent way.

DataOutputStream methods: writeInt, writeLong, writeDouble, writeFloat, writeBoolean, writeUTF
DataInputStream methods: readInt, readLong, readDouble, readFloat, readBoolean, readUTF

Critical: data written with DataOutputStream MUST be read back in the exact same order using DataInputStream.`,
        code: `// Writing primitives
DataOutputStream dos = new DataOutputStream(
    new FileOutputStream("data.bin"));
dos.writeInt(42);
dos.writeDouble(3.14);
dos.writeUTF("Hello");
dos.close();

// Reading them back — SAME ORDER
DataInputStream dis = new DataInputStream(
    new FileInputStream("data.bin"));
int i = dis.readInt();        // 42
double d = dis.readDouble();  // 3.14
String s = dis.readUTF();     // "Hello"
dis.close();`
      },
      {
        title: 'BufferedInputStream / BufferedOutputStream',
        content: `Buffered streams wrap another stream and add an internal buffer for efficiency. Instead of reading/writing one byte at a time (expensive system calls), they read/write in larger chunks internally.

BufferedWriter has a newLine() method for platform-independent line separator.
flush() must be called to ensure buffered data is written to underlying stream.`,
        code: `// Buffered reading
BufferedInputStream bis = new BufferedInputStream(
    new FileInputStream("large.dat"));
int data;
while ((data = bis.read()) != -1) {
    // processes from buffer — efficient
}
bis.close();

// Buffered writing
BufferedWriter bw = new BufferedWriter(
    new FileWriter("output.txt"));
bw.write("Line 1");
bw.newLine();
bw.write("Line 2");
bw.flush(); // flush buffer to file
bw.close();`
      },
      {
        title: 'SequenceInputStream',
        content: `SequenceInputStream reads data from multiple input streams in sequence, as if they were concatenated into a single stream. The constructor accepts two InputStreams or an Enumeration of InputStreams.`,
        code: `// Concatenating two files into one read pass
FileInputStream f1 = new FileInputStream("part1.txt");
FileInputStream f2 = new FileInputStream("part2.txt");
SequenceInputStream sis = new SequenceInputStream(f1, f2);

int data;
while ((data = sis.read()) != -1) {
    System.out.print((char) data);
}
sis.close(); // also closes f1 and f2`
      }
    ]
  },
  {
    id: 'ch4',
    number: 4,
    title: 'Random Access Files',
    subtitle: 'RandomAccessFile and seek() operations',
    icon: 'FileCog',
    color: 'neon-text-green',
    topics: [
      {
        title: 'RandomAccessFile Class',
        content: `The RandomAccessFile class allows simultaneous read and write operations on a file. Unlike sequential streams which read linearly, RandomAccessFile supports a file pointer that can be moved anywhere in the file.

Constructor modes:
• "r"  — read-only
• "rw" — read-write (creates file if it does not exist)

Key methods:
• seek(long pos) — moves the file pointer to byte position pos
• getFilePointer() — returns current byte position of the pointer
• length() — returns total file length in bytes
• readInt(), readDouble(), readUTF() — read primitives at current position
• writeInt(), writeDouble(), writeUTF() — write primitives at current position`,
        code: `RandomAccessFile raf = new RandomAccessFile("records.dat", "rw");

// Write at position 0
raf.seek(0);
raf.writeInt(100);     // writes 4 bytes
raf.writeDouble(3.14); // writes 8 bytes (total so far: 12 bytes)

// Jump back and read
raf.seek(0);
int i = raf.readInt();       // 100
double d = raf.readDouble(); // 3.14

// Append to end of file
raf.seek(raf.length());
raf.writeUTF("appended");

raf.close();`
      },
      {
        title: 'Sequential vs Random Access',
        content: `Sequential streams (FileInputStream, etc.) can only read forward — you cannot go back without reopening the stream. They are ideal for processing data once in order.

RandomAccessFile supports both reading and writing in any order by moving the file pointer. This is ideal for:
• Fixed-length record databases (jump to record n by seeking to n * recordSize)
• Updating specific fields without rewriting the whole file
• Implementing file-based data structures

To append data: raf.seek(raf.length()) positions the pointer at the end.`
      }
    ]
  },
  {
    id: 'ch5',
    number: 5,
    title: 'JDBC',
    subtitle: 'Java Database Connectivity API',
    icon: 'Server',
    color: 'neon-text-blue',
    topics: [
      {
        title: 'JDBC Architecture',
        content: `JDBC (Java Database Connectivity) is an API that enables Java applications to interact with relational databases. It provides a set of interfaces and classes for sending SQL queries and retrieving results.

JDBC API is defined in the java.sql package. Key interfaces:
• Driver — database-specific implementation
• Connection — represents a connection to a database
• Statement — used to execute SQL queries
• PreparedStatement — precompiled SQL statement (prevents SQL injection)
• ResultSet — table of results returned by a query
• DatabaseMetaData — information about the database

The standard 5-step JDBC workflow:
1. Load the driver
2. Establish the connection
3. Create a statement
4. Execute the query
5. Process the ResultSet`
      },
      {
        title: 'JDBC Step-by-Step',
        content: `Step 1 — Load Driver: Class.forName("com.mysql.jdbc.Driver")
Step 2 — Establish Connection: DriverManager.getConnection(url, user, pass)
  URL format: jdbc:subprotocol:subname  e.g. "jdbc:mysql://localhost/dbname"
Step 3 — Create Statement: connection.createStatement()
Step 4 — Execute Query:
  • executeQuery(sql) — for SELECT, returns ResultSet
  • executeUpdate(sql) — for INSERT/UPDATE/DELETE, returns row count
Step 5 — Process ResultSet: Iterate with rs.next(), read columns with rs.getString(), rs.getInt(), etc.`,
        code: `import java.sql.*;

public class JDBCExample {
    public static void main(String[] args) throws Exception {
        // Step 1: Load driver
        Class.forName("com.mysql.jdbc.Driver");

        // Step 2: Establish connection
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost/school", "root", "pass");

        // Step 3: Create statement
        Statement stmt = con.createStatement();

        // Step 4: Execute query
        ResultSet rs = stmt.executeQuery(
            "SELECT id, name FROM students");

        // Step 5: Process results
        while (rs.next()) {
            System.out.println(rs.getInt("id") +
                               " | " + rs.getString("name"));
        }

        rs.close();
        stmt.close();
        con.close();
    }
}`
      },
      {
        title: 'Database Metadata',
        content: `DatabaseMetaData provides information about the database itself (name, version, supported features, tables list, etc.).

ResultSetMetaData provides information about the columns in a ResultSet (column count, column names, data types).`,
        code: `// Database metadata
DatabaseMetaData dbmd = con.getMetaData();
System.out.println("DB: " + dbmd.getDatabaseProductName());
System.out.println("Version: " + dbmd.getDatabaseProductVersion());

// ResultSet metadata
ResultSet rs = stmt.executeQuery("SELECT * FROM employees");
ResultSetMetaData rsmd = rs.getMetaData();
int cols = rsmd.getColumnCount();
for (int i = 1; i <= cols; i++) {
    System.out.println(rsmd.getColumnName(i) +
                       " : " + rsmd.getColumnTypeName(i));
}`
      }
    ]
  },
  {
    id: 'ch6',
    number: 6,
    title: 'GUI — JavaFX',
    subtitle: 'Graphical User Interfaces with JavaFX',
    icon: 'Monitor',
    color: 'neon-text-cyan',
    topics: [
      {
        title: 'GUI Evolution: AWT → Swing → JavaFX',
        content: `AWT (Abstract Window Toolkit): Java's first GUI toolkit. Heavyweight components delegated to native OS widgets. Limited and platform-dependent look.

Swing: Built on AWT. Lightweight, pure-Java components. Pluggable look-and-feel. Extended AWT with J-prefixed components (JButton, JFrame, JPanel). Part of javax.swing.

JavaFX: Modern replacement for Swing. Features:
• Scene Graph — hierarchical tree of nodes
• FXML — XML-based UI layout
• CSS Styling — style components like HTML
• Built-in animations and effects
• Hardware-accelerated rendering`
      },
      {
        title: 'JavaFX Application Structure',
        content: `A JavaFX application extends Application and overrides the start(Stage stage) method. The Stage is the top-level window. A Scene holds the scene graph. Layout panes organize controls.

Key layout panes:
• HBox — horizontal layout
• VBox — vertical layout
• GridPane — grid-based layout
• BorderPane — 5-region layout (top, bottom, left, right, center)
• StackPane — stack nodes on top of each other
• FlowPane — flows children like text`,
        code: `import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class HelloFX extends Application {
    @Override
    public void start(Stage stage) {
        Button btn = new Button("Click Me");
        btn.setOnAction(e -> System.out.println("Clicked!"));

        VBox root = new VBox(10, btn); // spacing = 10
        Scene scene = new Scene(root, 400, 300);
        stage.setTitle("Hello JavaFX");
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}`
      },
      {
        title: 'Event-Driven Programming',
        content: `JavaFX uses event-driven programming: the application waits for user actions (events) and responds with event handlers.

Event handler approaches:
1. Lambda expression (most common): btn.setOnAction(e -> handler());
2. Anonymous inner class: btn.setOnAction(new EventHandler<ActionEvent>() {...})
3. Implementing EventHandler<ActionEvent> interface

Common events: ActionEvent (button click), MouseEvent (mouse actions), KeyEvent (keyboard input).`
      }
    ]
  },
  {
    id: 'ch7',
    number: 7,
    title: 'Multithreading',
    subtitle: 'Concurrent execution, synchronization & cooperation',
    icon: 'Cpu',
    color: 'neon-text-violet',
    topics: [
      {
        title: 'Thread Basics',
        content: `A thread is a single sequential flow of control within a program. Multithreading allows multiple threads to execute concurrently, sharing the same process memory.

Two ways to create a thread:
1. Extend Thread class and override run()
2. Implement Runnable interface and pass to Thread constructor (preferred — allows extending another class)

Thread lifecycle states: New → Runnable → Running → Blocked/Waiting → Dead`,
        code: `// Method 1: Extend Thread
class MyThread extends Thread {
    public void run() {
        System.out.println("Thread: " + getName());
    }
}

// Method 2: Implement Runnable (preferred)
class MyRunnable implements Runnable {
    public void run() {
        System.out.println("Running: " + Thread.currentThread().getName());
    }
}

// Starting threads
new MyThread().start();
new Thread(new MyRunnable()).start();
new Thread(() -> System.out.println("Lambda thread")).start();`
      },
      {
        title: 'Thread Synchronization',
        content: `A race condition occurs when multiple threads access and modify shared data concurrently, leading to unpredictable results.

Synchronization mechanisms:
• synchronized keyword — locks the object's intrinsic monitor
• synchronized method — entire method is atomic
• synchronized block — finer-grained locking
• java.util.concurrent.locks.Lock — explicit lock with lock() / unlock()
• ReentrantLock — most common Lock implementation

Only one thread can execute a synchronized block/method on the same object at a time.`,
        code: `// Synchronized method
class Counter {
    private int count = 0;
    public synchronized void increment() { count++; }
    public synchronized int getCount() { return count; }
}

// Explicit Lock
import java.util.concurrent.locks.*;
class SafeCounter {
    private int count = 0;
    private final Lock lock = new ReentrantLock();

    public void increment() {
        lock.lock();
        try {
            count++;
        } finally {
            lock.unlock(); // always unlock in finally!
        }
    }
}`
      },
      {
        title: 'Thread Cooperation (await/signal)',
        content: `Condition variables allow threads to coordinate using await() and signal()/signalAll() on a Lock's Condition object. This is the modern replacement for the deprecated wait()/notify() pattern.

await() — releases the lock and waits until signaled
signal() — wakes one waiting thread
signalAll() — wakes all waiting threads`,
        code: `import java.util.concurrent.locks.*;

class BoundedBuffer {
    private final Lock lock = new ReentrantLock();
    private final Condition notFull  = lock.newCondition();
    private final Condition notEmpty = lock.newCondition();
    private int[] items = new int[10];
    private int count, putIdx, takeIdx;

    public void put(int x) throws InterruptedException {
        lock.lock();
        try {
            while (count == items.length) notFull.await();
            items[putIdx] = x;
            putIdx = (putIdx + 1) % items.length;
            count++;
            notEmpty.signal();
        } finally { lock.unlock(); }
    }
}`
      }
    ]
  },
  {
    id: 'ch8',
    number: 8,
    title: 'Java Applets',
    subtitle: 'Internet-based GUI components & lifecycle',
    icon: 'Globe',
    color: 'neon-text-green',
    topics: [
      {
        title: 'Applet Overview',
        content: `A Java Applet is a small Java program that runs inside a web browser or applet viewer. Applets were embedded in HTML pages using the <applet> or <object> tag, delivering bytecode over the network.

Applets extend java.applet.Applet (or javax.swing.JApplet for Swing-based applets). They do NOT have a main() method — the browser's JVM controls their lifecycle.

Note: Applets are largely deprecated in modern Java and browsers, but remain relevant for exam purposes.`
      },
      {
        title: 'Applet Lifecycle Methods',
        content: `The browser calls these lifecycle methods in sequence:

1. init() — called once when the applet is first loaded. Use for one-time initialization (like a constructor).
2. start() — called each time the applet becomes visible (after init, and after stop when user returns to the page).
3. paint(Graphics g) — called to render the applet. Called by the browser whenever it needs to be redrawn.
4. stop() — called when the user navigates away from the page. Pause any threads here.
5. destroy() — called when the applet is being removed from memory. Free resources here.`,
        code: `import java.applet.Applet;
import java.awt.Graphics;

public class HelloApplet extends Applet {
    String message;

    @Override
    public void init() {
        message = getParameter("msg");
        if (message == null) message = "Hello, World!";
    }

    @Override
    public void start() {
        // resume activity
    }

    @Override
    public void paint(Graphics g) {
        g.drawString(message, 20, 20);
    }

    @Override
    public void stop() {
        // pause activity
    }

    @Override
    public void destroy() {
        // cleanup
    }
}`
      },
      {
        title: 'Embedding in HTML',
        content: `Applets are embedded in HTML using the <applet> tag:`,
        code: `<!-- HTML embedding -->
<applet code="HelloApplet.class" width="300" height="200">
    <param name="msg" value="Welcome to Applets!"/>
    Your browser does not support Java applets.
</applet>`
      }
    ]
  },
  {
    id: 'ch9',
    number: 9,
    title: 'Web Servlets',
    subtitle: 'Java server-side web components',
    icon: 'Layers',
    color: 'neon-text-blue',
    topics: [
      {
        title: 'Servlet Architecture',
        content: `A Servlet is a Java class that runs on a web server and handles HTTP requests from clients (browsers). Servlets implement the server-side of the request-response model.

Key components:
• Web Server (e.g. Apache Tomcat) — the Servlet Container
• HttpServlet — base class for HTTP servlets
• HttpServletRequest — encapsulates the incoming HTTP request
• HttpServletResponse — encapsulates the outgoing HTTP response

The servlet container manages the lifecycle of servlets: loading, instantiation, initialization, handling requests, and destruction.`
      },
      {
        title: 'Servlet Lifecycle',
        content: `1. init(ServletConfig config) — called once by the container after instantiation. One-time setup.
2. service(HttpServletRequest req, HttpServletResponse res) — called for every request. Dispatches to doGet() or doPost().
3. doGet() — handles HTTP GET requests
4. doPost() — handles HTTP POST requests
5. destroy() — called once before the servlet is removed from service. Cleanup resources.`,
        code: `import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;

@WebServlet("/hello")
public class HelloServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest request,
                         HttpServletResponse response)
                         throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        String name = request.getParameter("name");
        out.println("<html><body>");
        out.println("<h1>Hello, " + name + "!</h1>");
        out.println("</body></html>");
    }

    @Override
    protected void doPost(HttpServletRequest request,
                          HttpServletResponse response)
                          throws ServletException, IOException {
        // handle POST form submission
        String data = request.getParameter("data");
        // process...
        response.sendRedirect("/result");
    }
}`
      },
      {
        title: 'GET vs POST',
        content: `GET: Parameters are appended to the URL as query string (?key=value). Visible in the browser's address bar. Bookmarkable. Limited data size. Use for reading/fetching data.

POST: Parameters are sent in the HTTP request body. Not visible in URL. Larger data capacity. Use for creating/modifying data (form submissions, file uploads).

The HttpServletRequest methods:
• getParameter(name) — returns first value of named parameter
• getParameterValues(name) — returns all values (e.g. checkboxes)
• getParameterNames() — returns all parameter names`
      }
    ]
  }
]
